/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.awt.event.KeyEvent;
import java.util.Timer;
import java.util.TimerTask;


/**
 *
 * @author Yova
 */
public class frmCanvas extends javax.swing.JFrame {
    private Dibujo dib = new Dibujo(); 
    /**
     * Creates new form frmCanvas
     */
    
    private final Timer timer;
    
    public frmCanvas() {
        initComponents();
        this.setLocationRelativeTo(null);
        dib = new Dibujo(); 
        jLienzo.add(dib);
        jLienzo.repaint();
        dib.repaint();
        
        timer = new Timer();
        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                
                mover();
                dib.repaint();
                dib.cnt++;
                
                if (dib.cnt == 3){
                   dibPiez();
                   dib.cnt = 0;
                }
            }
        }, 0, 500);
    }
    
    public void mover(){
        for(int y = dib.totFil-1; y>=0;y--){
            for(int x = 0; x<dib.totCol;x++){
                if (dib.mat[x][y] != 0){
                    if ((y+1) <= (dib.totFil-1)){
                        dib.mat[x][y+1] = dib.mat[x][y];
                        dib.mat[x][y] = 0;
                    }else{
                        dib.mat[x][y] = 0;
                    }
                    
                }
                
            }
        }
    }
    
    public void dibPiez(){
        int rnd = 1 + (int)(Math.random() * 4);
        switch (rnd) {
            case 1:
                {
                    int[][] mt = dib.mat;
                    mt[4][0]=2;
                    mt[5][0]=2;
                    mt[6][0]=2;
                    mt[5][1]=2;
                    break;
                }
            case 2:
                {
                    int[][] mt = dib.mat;
                    mt[4][0]=3;
                    mt[5][0]=3;
                    mt[4][1]=3;
                    mt[5][1]=3;
                    break;
                }
            case 3:
                {
                    int[][] mt = dib.mat;
                    mt[4][0]=1;
                    mt[4][1]=1;
                    mt[4][2]=1;
                    break;
                }
            default:
                break;
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLienzo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jLienzo.setBackground(new java.awt.Color(221, 221, 221));
        jLienzo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLienzo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLienzo.setMaximumSize(null);
        jLienzo.setOpaque(false);
        jLienzo.setPreferredSize(new java.awt.Dimension(350, 350));

        javax.swing.GroupLayout jLienzoLayout = new javax.swing.GroupLayout(jLienzo);
        jLienzo.setLayout(jLienzoLayout);
        jLienzoLayout.setHorizontalGroup(
            jLienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );
        jLienzoLayout.setVerticalGroup(
            jLienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLienzo, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLienzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        
        if (evt.getKeyCode() == KeyEvent.VK_DOWN){
        
        }else if (evt.getKeyCode() == KeyEvent.VK_UP){
        System.out.println("rib");
        }else if (evt.getKeyCode() == KeyEvent.VK_LEFT){
        
        }
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCanvas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCanvas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCanvas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCanvas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCanvas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel jLienzo;
    // End of variables declaration//GEN-END:variables
}
